version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"
  web:
    build: .
    ports:
      - "8081:8081"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
